# <span style="color:blue"> MBA em Ciência de Dados</span>
# <span style="color:blue">Programação para Ciência de Dados</span>

## <span style="color:blue">Avaliação Numpy Parte II e Matplotlib</span>
**Material Produzido por Luis Gustavo Nonato**<br>
**Cemeai - ICMC/USP São Carlos**

### Exercício 1)

Qual dos códigos abaixo corretamente utiliza broadcasting para construir uma matriz cujas colunas são todas formadas pelos elementos [0,1,2,3]?

```python
A = np.zeros((4,4))
v = np.arange(4)
```

Escolha uma:<br>

<b>a.</b>
```python
A[:] = v.reshape(4,1) 
```

<b>b.</b>
```python
A[:] = v 
A = A.T
```

<b>c.</b>
```python
A[:] = v[:,np.newaxis]
```

<b>d</b>. Todas as alternativas estão corretas

In [80]:
import numpy as np

A = np.zeros((4,4))
v = np.arange(4)

A[:] = v.reshape(4,1)

A[:] = v[:,np.newaxis]

A[:] = v 
A = A.T

print(A)
print()
print("Resposta: Todas as alternativas estão corretas")

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]]

Resposta: Todas as alternativas estão corretas


### Exercício 2)

Qual das alternativas corretamente explica como o array W está sendo calculando no código abaixo?
```python
u = np.random.randint(0,30,7)
v = np.random.randint(0,30,10).reshape(10,1)

W = v + u
```

Escolha uma:<br>
<b>a. O array `W` é uma matriz com 10 linhas e 7 colunas gerado a partir da soma das matriz obtidas do broadcasting do array `v` em 7 colunas e do array `u` em 10 linhas.</b><br>
<b>b. O array W é uma matriz com 7 linhas e 10 colunas gerado a partir da soma das matriz obtidas do broadcasting do array v em 7 linhas e o array u em 10 linhas.</b><br>
<b>c. O array W possui 10 elementos como resultado da soma dos arrays u e v , onde u é complementado com zeros durante o broadcasting.</b><br>
<b>d. O array W possui 7 elementos como resultado da soma dos arrays u e v , onde os três últimos elementos de v são descartados no broadcasting.</b><br>

In [12]:
import numpy as np

u = np.random.randint(0,30,7)
v = np.random.randint(0,30,10).reshape(10,1)

W = v + u

print(W)
print()
print("Resposta: O array W é uma matriz com 10 linhas e 7 colunas gerado a partir da soma das matriz obtidas do broadcasting do array v em 7 colunas e do array u em 10 linhas.")

[[39 40 38 45 28 34 46]
 [22 23 21 28 11 17 29]
 [25 26 24 31 14 20 32]
 [45 46 44 51 34 40 52]
 [26 27 25 32 15 21 33]
 [31 32 30 37 20 26 38]
 [41 42 40 47 30 36 48]
 [50 51 49 56 39 45 57]
 [37 38 36 43 26 32 44]
 [21 22 20 27 10 16 28]]

Resposta: O array W é uma matriz com 10 linhas e 7 colunas gerado a partir da soma das matriz obtidas do broadcasting do array v em 7 colunas e do array u em 10 linhas.


### Exercício 3)
Considere a matriz abaixo. Utilizando redução, encontre o índice da linha que possui a maior soma dos elementos.
```python
A = np.array([[5, 2, 3, 6, 1, 5, 7, 7, 8, 9], [8, 8, 3, 5, 0, 1, 4, 8, 3, 7],
            [8, 0, 0, 4, 2, 0, 2, 6, 0, 3], [5, 0, 0, 4, 4, 3, 5, 8, 0, 0],
            [2, 4, 2, 5, 3, 4, 9, 8, 0, 0], [6, 7, 4, 8, 5, 1, 3, 5, 4, 1],
            [6, 8, 0, 5, 2, 9, 3, 6, 1, 6], [5, 5, 2, 9, 0, 5, 5, 8, 2, 4],
            [8, 8, 1, 8, 4, 1, 8, 9, 7, 6], [5, 6, 0, 9, 0, 4, 9, 0, 2, 0]])
```
Escolha uma:<br>
<b>a. linha 9</b><br>
<b>b. linha 8</b><br>
<b>c. linha 0</b><br>
<b>d. linha 6</b><br>

In [29]:
import numpy as np

A = np.array([[5, 2, 3, 6, 1, 5, 7, 7, 8, 9], [8, 8, 3, 5, 0, 1, 4, 8, 3, 7],
            [8, 0, 0, 4, 2, 0, 2, 6, 0, 3], [5, 0, 0, 4, 4, 3, 5, 8, 0, 0],
            [2, 4, 2, 5, 3, 4, 9, 8, 0, 0], [6, 7, 4, 8, 5, 1, 3, 5, 4, 1],
            [6, 8, 0, 5, 2, 9, 3, 6, 1, 6], [5, 5, 2, 9, 0, 5, 5, 8, 2, 4],
            [8, 8, 1, 8, 4, 1, 8, 9, 7, 6], [5, 6, 0, 9, 0, 4, 9, 0, 2, 0]])

B = np.array([np.sum(A[0]),np.sum(A[1]),
             np.sum(A[2]),np.sum(A[3]),
             np.sum(A[4]),np.sum(A[5]),
             np.sum(A[6]),np.sum(A[7]),
             np.sum(A[8]),np.sum(A[9])]).reshape(10,1)

print(B)
elemento = np.argmax(B)
print()
print("Resposta: linha",elemento)

[[53]
 [47]
 [25]
 [29]
 [37]
 [44]
 [46]
 [45]
 [60]
 [35]]

Resposta: linha 8


### Exercício 4)
Considerando a matriz A do exercício anterior, qual o índice da coluna que possui a menor média de valores?

Escolha uma:<br>
<b>a. coluna 9</b><br>
<b>b. coluna 0</b><br>
<b>c. coluna 2</b><br>
<b>d. coluna 8</b><br>

In [31]:
import numpy as np

A = np.array([[5, 2, 3, 6, 1, 5, 7, 7, 8, 9], [8, 8, 3, 5, 0, 1, 4, 8, 3, 7],
            [8, 0, 0, 4, 2, 0, 2, 6, 0, 3], [5, 0, 0, 4, 4, 3, 5, 8, 0, 0],
            [2, 4, 2, 5, 3, 4, 9, 8, 0, 0], [6, 7, 4, 8, 5, 1, 3, 5, 4, 1],
            [6, 8, 0, 5, 2, 9, 3, 6, 1, 6], [5, 5, 2, 9, 0, 5, 5, 8, 2, 4],
            [8, 8, 1, 8, 4, 1, 8, 9, 7, 6], [5, 6, 0, 9, 0, 4, 9, 0, 2, 0]])

B = np.array([np.mean(A[0]),np.mean(A[1]),
             np.mean(A[2]),np.mean(A[3]),
             np.mean(A[4]),np.mean(A[5]),
             np.mean(A[6]),np.mean(A[7]),
             np.mean(A[8]),np.mean(A[9])])

print(B)
elemento = np.argmin(B)
print()
print("Resposta: coluna",elemento)

[5.3 4.7 2.5 2.9 3.7 4.4 4.6 4.5 6.  3.5]

Resposta: coluna 2


### Exercício 5)
Suponha que a variável A no código abaixo é uma matriz com linhas e colunas. O que o código está realizando?
```python
Aargs = np.argsort(A)
A[np.arange(A.shape[0]),Aargs[:,-1]] = -1
```
Escolha uma:<br>
<b>a. Substituindo o menor valor de cada coluna por -1</b><br>
<b>b. Substituindo o maior valor de cada linha por -1</b><br>
<b>c. Substituindo o maior valor de cada coluna por -1</b><br>
<b>d. Substituindo o menor valor de cada linha por -1</b><br>

In [76]:
import numpy as np

A = np.array([[1,  2, 3],
              [2,  3,  1],
              [3,  2, 1]])
print("Matriz original:")
print(A)
Aargs = np.argsort(A)
print()
print("np.argsort(A) -> retorna o índice de cada elemento de A ordenados do menor para o maior")
print(Aargs)
print()
print("Aargs[:,-1] -> retorna o maior índice de cada linha de A, ou seja, vai retornar o maior número de cada linha de A")
print(Aargs[:,-1])

print()
A[np.arange(A.shape[0]),Aargs[:,-1]] = -1
print("A[np.arange(A.shape[0]),Aargs[:,-1]] = -1 -> retorna para cada linha de A, o maior valor encontrado e substitui por -1")
print(A)
print()
print("Resposta: Substituindo o maior valor de cada linha por -1")

Matriz original:
[[1 2 3]
 [2 3 1]
 [3 2 1]]

np.argsort(A) -> retorna o índice de cada elemento de A ordenados do menor para o maior
[[0 1 2]
 [2 0 1]
 [2 1 0]]

Aargs[:,-1] -> retorna o maior índice de cada linha de A, ou seja, vai retornar o maior número de cada linha de A
[2 1 0]

A[np.arange(A.shape[0]),Aargs[:,-1]] = -1 -> retorna para cada linha de A, o maior valor encontrado e substitui por -1
[[ 1  2 -1]
 [ 2 -1  1]
 [-1  2  1]]

Resposta: Substituindo o maior valor de cada linha por -1
