# <span style="color:blue"> MBA em Ciência de Dados</span>
# <span style="color:blue">Programação para Ciência de Dados</span>

## <span style="color:blue">Avaliação Numpy Parte I</span>
**Material Produzido por Luis Gustavo Nonato**<br>
**Cemeai - ICMC/USP São Carlos**

### Exercício 1)

Considere o array <font color='red'>X</font> como descrito abaixo:
```python
[[0 1 2 3 4]
 [5 6 7 8 9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
```
Qual dos códigos abaixo retorna um array com os elementos 12, 18 e 6?

Escolha uma:<br>

<b>a. print(X[[2,3,1],[2,3,1]])</b><br>
<b>b. print(X[:,[2,3,1])</b><br>
<b>c. print(X[1,2,3])</b><br>
<b>d. print([1,2,3],:)</b><br>

In [12]:
import numpy as np

X = np.array([[0,1,2,3,4],
              [5,6,7,8,9],
              [10,11,12,13,14],
              [15,16,17,18,19]])

print(X[[2,3,1],[2,3,1]])
print()
print("Resposta: print(X[[2,3,1],[2,3,1]])")

[12 18  6]

Resposta: print(X[[2,3,1],[2,3,1]])


### Exercício 2)
Considerando o array <font color='red'>X</font> do exercício 1), qual dos códigos abaixo retorna o array
```python
[[ 5 7 8]
 [10 12 13]]
```
Escolha uma:<br>
<b>a. print(X[1:3,:3])</b><br>
<b>b. print(X[1:3,[0,2,3]])</b><br>
<b>c. print(X[1:3,0:2:3]])</b><br>
<b>d. print(X[[1,2,3],[0,2,3]])</b><br>

In [36]:
import numpy as np

X = np.array([[0,1,2,3,4],
              [5,6,7,8,9],
              [10,11,12,13,14],
              [15,16,17,18,19]])

print(X[1:3,[0,2,3]])
print()
print("Resposta: print(X[1:3,[0,2,3]])")

[[ 5  7  8]
 [10 12 13]]

Resposta: print(X[1:3,[0,2,3]])


### Exercício 3)
Considere o numpy array <font color='red'>A</font> abaixo:
```python
[[ 2 19 16 1 12 7]
 [ 5 19 18 17 9 3]
 [16 4 18 11 4 2]
 [ 6 2 18 14 15 15]
 [ 4 8 1 14 19 13]]
```
Qual das alternativas abaixo corresponde a saída do comando:

```python
print(A.ndim, A.shape, A.size)
```

Escolha uma:<br>
<b>a. (5, 6) 2 2</b><br>
<b>b. 2 (5, 6) 30</b><br>
<b>c. 2 (5, 6) 2</b><br>
<b>d. (5, 6) 2 30</b><br>

In [53]:
import numpy as np

A = np.array([[2,19,16,1,12,7],
              [5,19,18,17,9,3],
              [16,4,18,11,4,2],
              [6,2,18,14,15,15],
              [4,8,1,14,19,13]])

print(A.ndim, A.shape, A.size)
print()
print("Resposta: 2 (5, 6) 30")

2 (5, 6) 30

Resposta: 2 (5, 6) 30


### Exercício 4)
Considere o numpy array <font color='red'>A</font> do exercício anterior. Escreva um código para criar uma máscara para selecionar todos os elementos pares do array e armazena-los em uma novo array unidimensional <font color='red'>B</font> . O resultado do comando
```python
print(B.size)
```
será:

Escolha uma:<br>
<b>a. 17</b><br>
<b>b. 16</b><br>
<b>c. 15</b><br>
<b>d. 13</b><br>

In [59]:
import numpy as np

A = np.array([[2,19,16,1,12,7],
              [5,19,18,17,9,3],
              [16,4,18,11,4,2],
              [6,2,18,14,15,15],
              [4,8,1,14,19,13]])

mask = (A%2 == 0)
B = A[mask]

print(B)
print()
print("Resposta: ",B.size)

[ 2 16 12 18 16  4 18  4  2  6  2 18 14  4  8 14]

Resposta:  16


### Exercício 5)
Ainda considerando o array <font color='red'>A</font> do exercício 3), que alternativa melhor explica o que o código abaixo está realizando:

```python
l_mask = [j%2!=0 for i in range(A.shape[0]) for j in range(A.shape[1])]
mask = np.array(l_mask).reshape(A.shape)
A[mask] = -1
```

Escolha uma:<br>
<b>a. troca os elementos ímpares da matriz por -1 utilizando uma máscara booleana</b><br>
<b>b. troca os elementos pares da matriz por -1 utilizando uma máscara booleana</b><br>
<b>c. insere elementos -1 nas linhas ímpares de <font color='red'>A</font> utilizando uma máscara booleana</b><br>
<b>d. insere elementos -1 nas colunas ímpares de <font color='red'>A</font> utilizando uma máscara booleana</b><br>

In [66]:
import numpy as np

A = np.array([[2,19,16,1,12,7],
              [5,19,18,17,9,3],
              [16,4,18,11,4,2],
              [6,2,18,14,15,15],
              [4,8,1,14,19,13]])

l_mask = [j%2!=0 for i in range(A.shape[0]) for j in range(A.shape[1])]
mask = np.array(l_mask).reshape(A.shape)
A[mask] = -1

print(A)
print()
print("Resposta: ","insere elementos -1 nas colunas ímpares de A utilizando uma máscara booleana")

[[ 2 -1 16 -1 12 -1]
 [ 5 -1 18 -1  9 -1]
 [16 -1 18 -1  4 -1]
 [ 6 -1 18 -1 15 -1]
 [ 4 -1  1 -1 19 -1]]

Resposta:  insere elementos -1 nas colunas ímpares de A utilizando uma máscara booleana
